# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# Use Node 8.x.
image: node:carbon

clone:
  # Don't clone history when pulling from Git; just get the latest version of the file.
  depth: 1

pipelines:
  branches:
    # All commits to master will run Code Coverage
    master:
      - step:
          name: Codacy Coverage
          script:
            # Copy SSH key so that we can pull additional submodules
            - mkdir -p /root/.ssh
            - cp id_rsa /root/.ssh/id_rsa
            - chmod 700 /root/.ssh/id_rsa
            - echo "Host bitbucket.org\n\tStrictHostKeyChecking no\n" >> /root/.ssh/config
            # Remove cached modules
            - rm -rf node_modules/ss-development
            # Install dependencies
            - npm install --no-package-lock
            # Run tests and push coverage to Codacy
            - npm run testWithCoverage
  tags:
    # Tagging a branch "test" will also cause it to generate Code Coverage (this is only really useful for ensuring the build instructions work)
    test:
      - step:
          name: Codacy Coverage
          script:
           # Copy SSH key so that we can pull additional submodules
            - mkdir -p /root/.ssh
            - cp id_rsa /root/.ssh/id_rsa
            - chmod 700 /root/.ssh/id_rsa
            - echo "Host bitbucket.org\n\tStrictHostKeyChecking no\n" >> /root/.ssh/config
            # Remove cached modules
            - rm -rf node_modules/ss-development
            # Install dependencies
            - npm install --no-package-lock
            # Run tests and push coverage to Codacy
            - npm run testWithCoverage