image: node:8.11.3

pipelines:
  branches:
    feature/pipelines/automatedeployment:
      - step:
          name: Build
          caches:
            - node
          script:
            # Copy SSH key so that we can pull additional submodules
            - mkdir -p /root/.ssh
            - cp id_rsa /root/.ssh/id_rsa
            - chmod 700 /root/.ssh/id_rsa
            - echo "Host bitbucket.org\n\tStrictHostKeyChecking no\n" >> /root/.ssh/config
            - npm install
            - npm run build
          artifacts:
            - Bundles/**
      - step:
          name: Commit Bundle File
          script:
            - echo "Made a change in build ${BITBUCKET_BUILD_NUMBER}" >> changes.txt
            - git add changes.txt
            - git add Bundles/lbreactcore.js
            - git commit -m "[skip ci] Update repo with latest bundle"
            - git push origin $BITBUCKET_BRANCH
            # Tagging branch with version number from package.json
            - declare -x VERSION=$(node -p -e "require('./package.json').version")
            - echo $VERSION
            # Create/Push tag to commit
            - git tag $VERSION # if tag already exists, this step will fail
            - git push origin $VERSION $BITBUCKET_BRANCH # branch name can't be the same as tag name
