// import the library
import { library } from "@fortawesome/fontawesome-svg-core";

// import your icons
import { faApple } from "@fortawesome/free-brands-svg-icons";
import { faBell, faBookmark } from "@fortawesome/free-regular-svg-icons";
import {
  faTimes,
  faCoffee,
  faEnvelope,
  faKey,
  faCircle,
  faCheck,
  faExclamation,
  faFlag,
  faChevronLeft,
  faChevronRight,
  faMapMarker,
  faUser
} from "@fortawesome/free-solid-svg-icons";
import {
  faAcorn,
  faClone,
  faDirections,
  faTimes as faTimesLight,
  faBoxingGlove,
  faPlusCircle,
  faChevronLeft as faChevronLeftLight,
  faChevronRight as faChevronRightLight
} from "@fortawesome/pro-light-svg-icons";
import {
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faAngleUp,
  faBoxingGlove as faBoxingGloveRegular,
  faCode,
  faLayerGroup,
  faMap,
  faShareAlt,
  faPlus,
  faMinus,
  faGlobe,
  faInfo,
  faCopy,
  faSignOut,
  faCog,
  faArrowFromBottom,
  faLocationArrow,
  faQuestionCircle,
  faToggleOff,
  faToggleOn,
  faEllipsisV,
  faShare,
  faFilter,
  faExpandArrows,
  faHighlighter
} from "@fortawesome/pro-regular-svg-icons";
import {
  faMoneyBill,
  faBoxingGlove as faBoxingGloveSolid
} from "@fortawesome/pro-solid-svg-icons";

library.add(
  faMoneyBill,
  faAcorn,
  faAngleUp,
  faAngleLeft,
  faAngleDown,
  faShareAlt,
  faAngleRight,
  faBoxingGlove,
  faBoxingGloveRegular,
  faBoxingGloveSolid,
  faCode,
  faCopy,
  faCog,
  faArrowFromBottom,
  faGlobe,
  faTimes,
  faSignOut,
  faTimesLight,
  faDirections,
  faToggleOff,
  faToggleOn,
  faEllipsisV,
  faPlusCircle,
  faExpandArrows,
  faHighlighter,
  faBell,
  faClone,
  faQuestionCircle,
  faMap,
  faMapMarker,
  faBookmark,
  faCoffee,
  faCheck,
  faInfo,
  faExclamation,
  faPlus,
  faMinus,
  faLocationArrow,
  faLayerGroup,
  faEnvelope,
  faKey,
  faCircle,
  faFilter,
  faFlag,
  faShare,
  faApple,
  faChevronLeft,
  faChevronRight,
  faChevronLeftLight,
  faChevronRightLight,
  faMapMarker,
  faUser
);
