/** import the Font Awesom library */
import { library } from "@fortawesome/fontawesome-svg-core";

/** Import Icons */

/** Solid */
import {
  faAnalytics,
  faAddressBook,
  faAddressCard,
  faBell as faBellSolid,
  faBookmark as faBookmarkSolid,
  faCheck,
  faCircle as faCircleSolid,
  faCogs,
  faDownload,
  faEnvelope as faEnvelopeSolid,
  faExclamation,
  faFileChartLine,
  faHomeAlt,
  faImages,
  faInfo,
  faInfoCircle as faInfoCircleSolid,
  faLayerMinus,
  faLayerPlus,
  faMapMarkedAlt,
  faMapMarkerAlt as faMapMarkerSolid,
  faMapPin,
  faMinus,
  faPhone,
  faPlus,
  faShareSquare,
  faSpinner,
  faStar as faStarSolid,
  faTimes,
  faUser,
  faUserHeadset,
  faUserPlus,
  faUsers,
  faUserTag,
} from "@fortawesome/pro-solid-svg-icons";

/** Regular (default) */
import {
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faAngleUp,
  faArrowToBottom,
  faArrowFromBottom,
  faBan,
  faBars,
  faBell,
  faBookmark,
  faCaretSquareUp,
  faChartBar,
  faChartScatter,
  faCheckCircle,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faCircle,
  faClone,
  faCog,
  faCommentAlt,
  faCommentsAlt,
  faCompressAlt,
  faCopy,
  faDirections,
  faEdit,
  faEllipsisH,
  faEllipsisV,
  faEnvelope,
  faEquals,
  faExchangeAlt,
  faExclamationTriangle,
  faExpandAlt,
  faExpandArrows,
  faExternalLinkAlt,
  faFileAlt,
  faFilter,
  faFolderOpen,
  faGlobe,
  faHashtag,
  faInfoCircle,
  faLayerGroup,
  faLink,
  faListUl,
  faLocationArrow,
  faLocationCircle,
  faMap,
  faMapMarkerAlt,
  faMinusSquare,
  faMinusCircle,
  faPaperclip,
  faPencil,
  faPencilRuler,
  faPlusSquare,
  faPlusCircle,
  faPrint,
  faQuestionCircle,
  faRedoAlt,
  faRulerCombined,
  faSave,
  faSearch,
  faSearchMinus,
  faSearchPlus,
  faShareAlt,
  faSignal,
  faSignalSlash,
  faSignIn,
  faSignOut,
  faSlidersH,
  faStar,
  faSyncAlt,
  faTable,
  faTags,
  faTrashAlt,
  faUndoAlt,
  faUserCog,
  faUserCircle,
  faUsersCog,
  faWifi,
  faWifiSlash,
} from "@fortawesome/pro-regular-svg-icons";

/** Light
 * (library placeholder)
 */
import { faNull } from "@fortawesome/pro-light-svg-icons";

/** Brands */
import {
  faApple,
  faFacebook,
  faFirefox,
  faGoogle,
  faInternetExplorer,
  faTwitterSquare,
  faWindows,
} from "@fortawesome/free-brands-svg-icons";

/** Create DMP icon library */
library.add(
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faAngleUp,
  faAddressBook,
  faAddressCard,
  faAnalytics,
  faApple,
  faArrowToBottom,
  faArrowFromBottom,
  faBan,
  faBars,
  faBell,
  faBellSolid,
  faBookmark,
  faBookmarkSolid,
  faCaretSquareUp,
  faChartBar,
  faChartScatter,
  faCheck,
  faCheckCircle,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faCircle,
  faCircleSolid,
  faClone,
  faCog,
  faCogs,
  faCommentAlt,
  faCommentsAlt,
  faCompressAlt,
  faCopy,
  faDirections,
  faDownload,
  faEdit,
  faEllipsisH,
  faEllipsisV,
  faEnvelope,
  faEnvelopeSolid,
  faEquals,
  faExchangeAlt,
  faExclamation,
  faExclamationTriangle,
  faExpandAlt,
  faExpandArrows,
  faExternalLinkAlt,
  faFacebook,
  faFileAlt,
  faFileChartLine,
  faFilter,
  faFirefox,
  faFolderOpen,
  faGlobe,
  faGoogle,
  faHashtag,
  faHomeAlt,
  faImages,
  faInfo,
  faInfoCircle,
  faInfoCircleSolid,
  faInternetExplorer,
  faLayerGroup,
  faLayerMinus,
  faLayerPlus,
  faLink,
  faListUl,
  faLocationArrow,
  faLocationCircle,
  faMap,
  faMapMarkedAlt,
  faMapMarkerAlt,
  faMapMarkerSolid,
  faMapPin,
  faMinus,
  faMinusCircle,
  faMinusSquare,
  faPaperclip,
  faPencil,
  faPencilRuler,
  faPhone,
  faPlus,
  faPlusCircle,
  faPlusSquare,
  faPrint,
  faQuestionCircle,
  faRedoAlt,
  faRulerCombined,
  faSave,
  faSearch,
  faSearchMinus,
  faSearchPlus,
  faShareAlt,
  faShareSquare,
  faSignal,
  faSignalSlash,
  faSignIn,
  faSignOut,
  faSlidersH,
  faSpinner,
  faStar,
  faStarSolid,
  faSyncAlt,
  faTable,
  faTags,
  faTimes,
  faTrashAlt,
  faTwitterSquare,
  faUndoAlt,
  faUser,
  faUserCircle,
  faUserCog,
  faUserHeadset,
  faUserPlus,
  faUsers,
  faUsersCog,
  faUserTag,
  faWifi,
  faWifiSlash,
  faWindows,
);
