/** import the Font Awesom library */
import { library } from "@fortawesome/fontawesome-svg-core";

/** Import Icons */

/** Solid */
import {
  faAnalytics,
  faAddressBook as faAddressBookSolid,
  faAddressCard,
  faAngleDown as faAngleDownSolid,
  faAngleLeft as faAngleLeftSolid,
  faAngleRight as faAngleRightSolid,
  faAngleUp as faAngleUpSolid,
  faBell as faBellSolid,
  faBookmark as faBookmarkSolid,
  faCalendarCheck,
  faCheck as faCheckSolid,
  faChevronDown as faChevronDownSolid,
  faChevronLeft as faChevronLeftSolid,
  faChevronRight as faChevronRightSolid,
  faChevronUp as faChevronUpSolid,
  faCircle as faCircleSolid,
  faClipboardList,
  faCogs,
  faConstruction,
  faDownload,
  faEnvelope as faEnvelopeSolid,
  faExclamation,
  faFileChartLine,
  faFileSearch,
  faHandHoldingUsd,
  faHomeAlt,
  faImages as faImagesSolid,
  faInfo as faInfoSolid,
  faInfoCircle as faInfoCircleSolid,
  faLayerMinus,
  faLayerPlus,
  faMapMarker as faMapMarkerSolid,
  faMapPin,
  faMinus,
  faPhone,
  faPlus as faPlusSolid,
  faShareSquare,
  faSpinner,
  faStar as faStarSolid,
  faTimes as faTimesSolid,
  faUser as faUserSolid,
  faUserHeadset,
  faUserPlus,
  faUsers,
  faUserTag,
} from "@fortawesome/pro-solid-svg-icons";

/** Regular (default) */
import {
  faAddressBook,
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faAngleUp,
  faArrowToBottom,
  faArrowFromBottom,
  faBan,
  faBars,
  faBell,
  faBookmark,
  faCalendarAlt,
  faCaretSquareUp,
  faChartBar,
  faChartScatter,
  faCheck,
  faCheckCircle,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faCircle,
  faClone,
  faCloudDownload,
  faCloudUpload,
  faCog,
  faComment,
  faCommentAlt,
  faCommentsAlt,
  faCompressAlt,
  faCopy,
  faDirections,
  faEdit,
  faEllipsisH,
  faEllipsisV,
  faEnvelope,
  faEquals,
  faExchangeAlt,
  faExclamationTriangle,
  faExpandAlt,
  faExpandArrows,
  faExternalLinkAlt,
  faEye,
  faFileAlt,
  faFilter,
  faFolderOpen,
  faGlobe,
  faHashtag,
  faInfo,
  faInfoCircle,
  faImages,
  faLayerGroup,
  faLink,
  faListUl,
  faLocationArrow,
  faLocationCircle,
  faMap,
  faMapMarkerAlt,
  faMapMarker,
  faMinusSquare,
  faMinusCircle,
  faPaperclip,
  faPencil,
  faPencilRuler,
  faPlus,
  faPlusSquare,
  faPlusCircle,
  faPrint,
  faQuestion,
  faQuestionCircle,
  faRedoAlt,
  faRulerCombined,
  faSave,
  faSearch,
  faSearchLocation,
  faSearchMinus,
  faSearchPlus,
  faShare,
  faShareAlt,
  faSignal,
  faSignalSlash,
  faSignIn,
  faSignOut,
  faSlidersH,
  faStar,
  faSyncAlt,
  faTable,
  faTags,
  faTimes,
  faTrashAlt,
  faUndoAlt,
  faUniversalAccess,
  faUser,
  faUserCog,
  faUserCircle,
  faUsersCog,
  faWifi,
  faWifiSlash,
} from "@fortawesome/pro-regular-svg-icons";

/** Light
 * (library placeholder)
 */
import { faNull } from "@fortawesome/pro-light-svg-icons";

/** Brands */
import {
  faApple,
  faFacebook,
  faFirefox,
  faGoogle,
  faInternetExplorer,
  faTwitterSquare,
  faWindows,
} from "@fortawesome/free-brands-svg-icons";

/** Create DMP icon library */
library.add(
  faAddressBook,
  faAddressBookSolid,
  faAddressCard,
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faAngleUp,
  faAngleDownSolid,
  faAngleLeftSolid,
  faAngleRightSolid,
  faAngleUpSolid,
  faAnalytics,
  faApple,
  faArrowToBottom,
  faArrowFromBottom,
  faBan,
  faBars,
  faBell,
  faBellSolid,
  faBookmark,
  faBookmarkSolid,
  faCalendarAlt,
  faCalendarCheck,
  faCaretSquareUp,
  faChartBar,
  faChartScatter,
  faCheck,
  faCheckSolid,
  faCheckCircle,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faChevronDownSolid,
  faChevronLeftSolid,
  faChevronRightSolid,
  faChevronUpSolid,
  faCircle,
  faCircleSolid,
  faClipboardList,
  faClone,
  faCloudDownload,
  faCloudUpload,
  faCog,
  faCogs,
  faComment,
  faCommentAlt,
  faCommentsAlt,
  faCompressAlt,
  faConstruction,
  faCopy,
  faDirections,
  faDownload,
  faEdit,
  faEllipsisH,
  faEllipsisV,
  faEnvelope,
  faEnvelopeSolid,
  faEquals,
  faExchangeAlt,
  faExclamation,
  faExclamationTriangle,
  faExpandAlt,
  faExpandArrows,
  faExternalLinkAlt,
  faEye,
  faFacebook,
  faFileAlt,
  faFileChartLine,
  faFileSearch,
  faFilter,
  faFirefox,
  faFolderOpen,
  faGlobe,
  faGoogle,
  faHandHoldingUsd,
  faHashtag,
  faHomeAlt,
  faImages,
  faImagesSolid,
  faInfo,
  faInfoSolid,
  faInfoCircle,
  faInfoCircleSolid,
  faInternetExplorer,
  faLayerGroup,
  faLayerMinus,
  faLayerPlus,
  faLink,
  faListUl,
  faLocationArrow,
  faLocationCircle,
  faMap,
  faMapMarkerAlt,
  faMapMarker,
  faMapMarkerSolid,
  faMapPin,
  faMinus,
  faMinusCircle,
  faMinusSquare,
  faPaperclip,
  faPencil,
  faPencilRuler,
  faPhone,
  faPlus,
  faPlusSolid,
  faPlusCircle,
  faPlusSquare,
  faPrint,
  faQuestion,
  faQuestionCircle,
  faRedoAlt,
  faRulerCombined,
  faSave,
  faSearch,
  faSearchLocation,
  faSearchMinus,
  faSearchPlus,
  faShare,
  faShareAlt,
  faShareSquare,
  faSignal,
  faSignalSlash,
  faSignIn,
  faSignOut,
  faSlidersH,
  faSpinner,
  faStar,
  faStarSolid,
  faSyncAlt,
  faTable,
  faTags,
  faTimes,
  faTimesSolid,
  faTrashAlt,
  faTwitterSquare,
  faUndoAlt,
  faUniversalAccess,
  faUser,
  faUserCircle,
  faUserCog,
  faUserHeadset,
  faUserPlus,
  faUsers,
  faUserSolid,
  faUsersCog,
  faUserTag,
  faWifi,
  faWifiSlash,
  faWindows,
);
