import React from "react";
import { Padding } from "helpers/Display";
import GenericSurface from "./GenericSurface.jsx";

const content = [
  {
    sectionTitle: "Foo",
    records: [
      {
        _DMP_ID: "100660192_194571250",
        _DESCRIPTOR: "450 N GRAND AVE, LOS ANGELES, CA 90012",
        _X_COORD: -118.24338,
        _XMAX: -118.2418,
        _XMIN: -118.24504,
        _Y_COORD: 34.059126,
        _YMAX: 34.060432,
        _YMIN: 34.05781,
        ACREAGE: 10.25,
        ADDRESS_ID: "US_06_037_159289302",
        AGGR_ACREAGE: 10.254133,
        AGGR_GROUP: "100660192_194571250",
        AGGR_LOT_COUNT: 1,
        AIR_CONDITIONING_TYPE_DESC: "",
        ALTERNATE_APN: "",
        APN: "5408-002-902",
        APN_UNF: "5408002902",
        ASMT_YEAR: "2019",
        ASSOCIATE_PARCEL_COUNT: 1,
        ASSR_ACREAGE: 10.25,
        ASSR_BOOK_PAGE: "",
        ASSR_SQFT: 446636,
        AVM_VALUE: null,
        BEDROOMS: null,
        BLDG_NUMBER: null,
        BLOCK_NUMBER: "",
        BSMT_1_CODE: "",
        BUILDING_SQFT: null,
        CAL_ACREAGE: 10.2533,
        CAL_SQFT: 446634,
        CENSUS_BLOCK_GROUP: "1",
        CENSUS_TRACT: "207101",
        CONDITION_CODE_DESC: "",
        CONSTRUCTION_CODE_DESC: "",
        COUNTY: "LOS ANGELES",
        DATE_NOVAL_TRANSFER: null,
        DATE_TRANSFER: null,
        DOC_NUMBER: "",
        DOC_NUMBER_NOVAL: "",
        DOC_TYPE_DESC: "",
        FIPS_CODE: "06037",
        FIREPLACE_TYPE: "",
        GARAGE_CODE_DESC: "",
        GEOMETRY: {},
        HEATING_DESC: "",
        IMPRV_PCT: null,
        INT_RATE_TYPE_1: "",
        INT_RATE_TYPE_2: "",
        LAND_SQFT: 446636,
        LANDUSE_CODE: "650",
        LANDUSE_DESC: "SCHOOL",
        LEGAL_1: "TRACT NO 26838 LOT 1",
        LIVING_SQFT: null,
        LNDR_FIRST_NAME_1: "",
        LNDR_LAST_NAME_1: "",
        LOAN_VALUE_1: null,
        LOAN_VALUE_2: null,
        LOCATION_ID: "US_06_037_5408002902",
        LOT_DEPTH: null,
        LOT_NUMBER: "1",
        LOT_WIDTH: null,
        MAP_LINK: "5408-002-902",
        MAP_REFERENCE_1: "-",
        OWNER_ADDRESS: "333 S BEAUDRY AVE",
        OWNER_CITY: "LOS ANGELES",
        OWNER_NAME_1: "L A UNIFIED SCHOOL DIST",
        OWNER_NAME_2: "",
        OWNER_OCCUPIED: "N",
        OWNER_STATE: "CA",
        OWNER_ZIP: "90017",
        OWNERSHIP_STATUS_CODE: "",
        OWNERSHIP_STATUS_DESC: "",
        PARCEL_APN: "5408002902",
        PARKING_SPACES: 0,
        PRICE_PER_ACRE: null,
        PRICE_PER_SQFT: null,
        PROPERTY_ID: "060371222436",
        RANGE: "",
        ROOF_CONSTRUCTION_DESC: "",
        ROOF_COVER_DESC: "",
        SALE_CODE_DESC: "",
        SECTION: "",
        SELLER_NAME: "",
        SITE_ADDR: "450 N GRAND AVE",
        SITE_CITY: "LOS ANGELES",
        SITE_STATE: "CA",
        SITE_ZIP: "90012",
        STORIES_NUMBER: "2",
        STYLE_DESC: "",
        SUBDIVISION: "",
        TAX_ACCT_NBR: "",
        TAX_AMOUNT: null,
        TAX_EXEMPTION_DESC: "",
        TAX_ID: "US_06_037_5408-002-902",
        TAX_YEAR: null,
        TD_DOC_NUMBER_1: "",
        TITLE_COMPANY_NAME: "",
        TOTAL_BATHS_CALCULATED: 0,
        TOTAL_ROOMS: null,
        TOWNSHIP: "",
        TRACT_NUMBER: "26838",
        UNITS_NUMBER: null,
        USE_CODE_MUNI: "8832",
        USE_CODE_STD_CTGR_DESC: "MISCELLANEOUS",
        USE_CODE_STD_DESC: "SCHOOL",
        VAL_ASSD: 3847860,
        VAL_ASSD_IMPRV: null,
        VAL_ASSD_LAND: 3847860,
        VAL_MARKET: null,
        VAL_TRANSFER: null,
        YR_BLT: null,
        YR_BLT_EFFECT: null,
        ZONING: "LAPF",
      },
    ],
    displayFields: [
      {
        label: "Site Address",
        value: "${records[0].SITE_ADDR} ${records[0].SITE_CITY}, ${records[0].SITE_STATE} ${records[0].SITE_CITY}",
      },
      {
        label: "Assessed Value",
        value: "${records[0].VAL_ASSD.toLocaleString('en-us', {style: 'currency', currency: 'USD'})}",
      },
    ],
    commands: [
      {
        label: "Add To List",
        icon: "List",
        onClick: () => { console.log("Add To List clicked"); },
      },
    ],
  },
  {
    title: "BAR",
  },
];

/*
    SITE_ADDR: "450 N GRAND AVE",
    SITE_CITY: "LOS ANGELES",
    SITE_STATE: "CA",
    SITE_ZIP: "90012",
*/

storiesOf("Blocks|Generic Surface", module)
  .addDecorator(Padding)
  .add("Foo", () => {
    return (
      <GenericSurface template={"SummaryPanel"} content={content} />
    );
  });
