import "@storybook/addon-a11y/register";
import "@storybook/addon-actions/register";
import "@storybook/addon-knobs/register";
import "@storybook/addon-links/register";
import "@storybook/addon-notes/register";
import "@storybook/addon-options/register";
// import '@storybook/addon-storysource/register';
import "@storybook/addon-viewport/register";
import "react-storybook-addon-chapters";
// import 'storybook-addon-styled-component-theme/dist/src/register';
// import 'storybook-readme/register';
